const fs = require('fs');
const L = [];
L.push('- [ ] 3. blog-springboot 公共模块');
L.push('  - [ ] 3.1 实现统一响应体 Result<T> 和 ResultCode 枚举');
L.push('    - 创建 com.blog.common.result.Result<T>，包含 code、message、data 字段及 success()、error() 静态工厂方法');
L.push('    - 创建 com.blog.common.result.ResultCode 枚举，定义 SUCCESS(200)、BAD_REQUEST(400)、UNAUTHORIZED(401)、FORBIDDEN(403)、NOT_FOUND(404)、INTERNAL_ERROR(500) 及业务错误码 1001-1006');
L.push('    - _需求：需求 9.1、需求 9.2、需求 10.1、需求 10.2_');
L.push('  - [ ] 3.2 实现业务异常 BusinessException');
L.push('    - 创建 com.blog.common.exception.BusinessException，继承 RuntimeException，持有 ResultCode 字段');
L.push('    - _需求：需求 9.4_');
L.push('  - [ ] 3.3 实现全局异常处理器 GlobalExceptionHandler');
L.push('    - 创建 com.blog.common.exception.GlobalExceptionHandler，使用 @RestControllerAdvice');
L.push('    - 分别处理 BusinessException（返回对应业务错误码）、MethodArgumentNotValidException（返回 code=400 及字段错误信息）、系统未捕获 Exception（返回 code=500 并记录堆栈）');
L.push('    - _需求：需求 9.3、需求 9.4、需求 9.5、需求 9.6、需求 10.3_');
L.push('  - [ ] 3.4 实现 BaseEntity 抽象基类');
L.push('    - 创建 com.blog.entity.BaseEntity，包含 createTime、createBy、updateTime、updateBy 四个字段，使用 @TableField(fill=...) 注解');
L.push('    - _需求：需求 2.3、需求 2.5_');
L.push('  - [ ] 3.5 实现 BlogMetaObjectHandler 自动填充处理器');
L.push('    - 创建 com.blog.common.handler.BlogMetaObjectHandler，实现 MetaObjectHandler 接口');
L.push('    - insertFill 填充 createTime、updateTime、createBy、updateBy；updateFill 填充 updateTime、updateBy');
L.push('    - 通过 StpUtil.isLogin() 判断当前用户，已登录取用户名，未登录填 "visitor"');
L.push('    - _需求：需求 2.3、需求 2.5_');
L.push('  - [ ] 3.6 实现请求日志拦截器 RequestLogInterceptor');
L.push('    - 创建 com.blog.common.interceptor.RequestLogInterceptor，实现 HandlerInterceptor');
L.push('    - preHandle 记录请求路径、HTTP 方法、请求参数；afterCompletion 记录响应耗时');
L.push('    - _需求：需求 9.8、需求 10.8_');
L.push('  - [ ] 3.7 配置 MyBatis-Plus（分页插件、逻辑删除）');
L.push('    - 创建 com.blog.config.MybatisPlusConfig，注册 MybatisPlusInterceptor 并添加 PaginationInnerInterceptor');
L.push('    - 在 application.yml 中配置 mybatis-plus.global-config.db-config.logic-delete-field=deleted、logic-delete-value=1、logic-not-delete-value=0');
L.push('    - _需求：需求 2.6、需求 2.11_');
L.push('  - [ ] 3.8 配置 Sa-Token 鉴权');
L.push('    - 创建 com.blog.config.SaTokenConfig，注册 Sa-Token 路由拦截器，拦截 /api/admin/** 路径，排除 /api/admin/auth/login');
L.push('    - 未登录时抛出异常，由 GlobalExceptionHandler 捕获并返回 code=401');
L.push('    - _需求：需求 1.6、需求 1.7_');
L.push('  - [ ] 3.9 配置 CORS 跨域');
L.push('    - 创建 com.blog.config.CorsConfig，允许前端域名跨域访问 /api/** 和 /api/admin/** 路径');
L.push('    - _需求：需求 9.10、需求 10.9_');
L.push('  - [ ] 3.10 配置 WebMvcConfig 注册拦截器');
L.push('    - 创建 com.blog.config.WebMvcConfig，实现 WebMvcConfigurer，注册 RequestLogInterceptor 拦截所有 /api/** 路径');
L.push('    - _需求：需求 9.8、需求 10.8_');
L.push('');
const existing = fs.readFileSync('.kiro/specs/personal-blog-system/tasks.md', 'utf8');
fs.writeFileSync('.kiro/specs/personal-blog-system/tasks.md', existing + L.join('\n') + '\n', 'utf8');
console.log('task3 ok');
