spring:
  datasource:
    url: jdbc:mysql://localhost:3307/neptune?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin

  redis:
    host: 127.0.0.1
    password:


